#spring.security.oauth2.client.registration.google.client-id=1017471706095-ja3cta2r4p3ep9csjq0ksdp09tnbqhhv.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
spring:
  application:
    name: auth
  data:
    mongodb:
      uri: mongodb+srv://nicholas1022:Pe020941989@cluster0.kou0eyi.mongodb.net/?retryWrites=true&w=majority
      database: apricot_demo
  jpa:
    generate-ddl: true
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
server:
  port: 9000
#specify prefix to all controller
#server.servlet.contextPath=/auth

#spring.main.web-application-type=reactive
#spring.main.allow-bean-definition-overriding=true